[install]
is_configured = true

[ui]
is_visible = false
label = BOTSv1 Sysmon Parsing

[launcher]
author = Mephistopplz
description = Search-time field extractions for BOTSv1 Sysmon XML events
version = 1.0.0

[package]
id = TA-botsv1-sysmon
